# Generated by Django 5.1.6 on 2025-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_min_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefeature',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='courselearningpoint',
            name='text',
        ),
        migrations.AddField(
            model_name='courselearningpoint',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
