# Generated by Django 5.1.6 on 2025-05-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_course_location_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('visa', 'Visa')], default='cash', max_length=20),
        ),
    ]
